Library_ROR/Library_System/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  #resource :session, :only => [:new, :create, :destroy]
  #match 'signup' => 'users#new', :as => :signup
  #match 'register' => 'users#create', :as => :register
  #match 'login' => 'sessions#new', :as => :login
  #match 'logout' => 'sessions#destroy', :as => :logout

  	#match 'activate/:activation_code' => 'users#activate', :as => activate, :activation_code => nil
 	#resources :support_issues 



  resources :cardholder_accounts
  get 'pages/home'
  root 'pages#home'


  resources :cardholder_personal_infos
  resources :materials
  resources :fines
  resources :checkouts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Library_ROR/Library_System/app/models/cardholder_account.rb
class CardholderAccount < ApplicationRecord

	has_one	    :cardhorder_personal_info	

	has_many    :checkouts

	has_many    :fines

	validates_uniqueness_of :cardholder_id

end

Library_ROR/Library_System/app/controllers/cardholder_accounts_controller.rb
class CardholderAccountsController < ApplicationController
  before_action :set_cardholder_account, only: [:show, :edit, :update, :destroy]

  # GET /cardholder_accounts
  # GET /cardholder_accounts.json
  def index
    @cardholder_accounts = CardholderAccount.all
  end

  # GET /cardholder_accounts/1
  # GET /cardholder_accounts/1.json
  def show
  end

  # GET /cardholder_accounts/new
  def new
    @cardholder_account = CardholderAccount.new
  end

  # GET /cardholder_accounts/1/edit
  def edit
  end

  # POST /cardholder_accounts
  # POST /cardholder_accounts.json
  def create
    @cardholder_account = CardholderAccount.new(cardholder_account_params)

    respond_to do |format|
      if @cardholder_account.save
        format.html { redirect_to @cardholder_account, notice: 'Cardholder account was successfully created.' }
        format.json { render :show, status: :created, location: @cardholder_account }
      else
        format.html { render :new }
        format.json { render json: @cardholder_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cardholder_accounts/1
  # PATCH/PUT /cardholder_accounts/1.json
  def update
    respond_to do |format|
      if @cardholder_account.update(cardholder_account_params)
        format.html { redirect_to @cardholder_account, notice: 'Cardholder account was successfully updated.' }
        format.json { render :show, status: :ok, location: @cardholder_account }
      else
        format.html { render :edit }
        format.json { render json: @cardholder_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cardholder_accounts/1
  # DELETE /cardholder_accounts/1.json
  def destroy
    @cardholder_account.destroy
    respond_to do |format|
      format.html { redirect_to cardholder_accounts_url, notice: 'Cardholder account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cardholder_account
      @cardholder_account = CardholderAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cardholder_account_params
      params.require(:cardholder_account).permit(:firstname, :lastname, :cardholder_id)
    end
end

Library_ROR/Library_System/app/helpers/cardholder_accounts_helper.rb
module CardholderAccountsHelper
end

Library_ROR/Library_System/app/views/cardholder_accounts/_form.html.erb
<%= form_for(cardholder_account) do |f| %>
  <% if cardholder_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cardholder_account.errors.count, "error") %> prohibited this cardholder_account from being saved:</h2>

      <ul>
      <% cardholder_account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %>
    <%= f.text_field :firstname %>
  </div>

  <div class="field">
    <%= f.label :lastname %>
    <%= f.text_field :lastname %>
  </div>

  <div class="field">
    <%= f.label :cardholder_id %>
    <%= f.number_field :cardholder_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Library_ROR/Library_System/app/views/cardholder_accounts/edit.html.erb
<h1>Editing Cardholder Account</h1>

<%= render 'form', cardholder_account: @cardholder_account %>

<%= link_to 'Show', @cardholder_account %> |
<%= link_to 'Back', cardholder_accounts_path %>

Library_ROR/Library_System/app/views/cardholder_accounts/index.html.erb
<!--<p id="notice"><%= notice %></p>-->

<h1 align="center">Cardholder Accounts</h1>
<div class="container">
    <%= button_to "Personal Infos", cardholder_personal_infos_path, method: :get %>
<table class="table">
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Cardholder</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cardholder_accounts.each do |cardholder_account| %>
      <tr>
        <td><%= cardholder_account.firstname %></td>
        <td><%= cardholder_account.lastname %></td>
        <td><%= cardholder_account.cardholder_id %></td>
        <td><%= link_to 'Show', cardholder_account %></td>
        <td><%= link_to 'Edit', edit_cardholder_account_path(cardholder_account) %></td>
        <td><%= link_to 'Destroy', cardholder_account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>


<%= link_to 'New Cardholder Account', new_cardholder_account_path %>

Library_ROR/Library_System/app/views/cardholder_accounts/new.html.erb
<h1>New Cardholder Account</h1>

<%= render 'form', cardholder_account: @cardholder_account %>

<%= link_to 'Back', cardholder_accounts_path %>

Library_ROR/Library_System/app/views/cardholder_accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @cardholder_account.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @cardholder_account.lastname %>
</p>

<p>
  <strong>Cardholder:</strong>
  <%= @cardholder_account.cardholder_id %>
</p>

<%= link_to 'Edit', edit_cardholder_account_path(@cardholder_account) %> |
<%= link_to 'Back', cardholder_accounts_path %>