Library_ROR/Library_System/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  #resource :session, :only => [:new, :create, :destroy]
  #match 'signup' => 'users#new', :as => :signup
  #match 'register' => 'users#create', :as => :register
  #match 'login' => 'sessions#new', :as => :login
  #match 'logout' => 'sessions#destroy', :as => :logout

  	#match 'activate/:activation_code' => 'users#activate', :as => activate, :activation_code => nil
 	#resources :support_issues 



  resources :cardholder_accounts
  get 'pages/home'
  root 'pages#home'


  resources :cardholder_personal_infos
  resources :materials
  resources :fines
  resources :checkouts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Library_ROR/Library_System/app/models/cardholder_personal_info.rb
class CardholderPersonalInfo < ApplicationRecord

	#belongs_to  :cardholder_account

	validates_uniqueness_of :cardholder_id
end

Library_ROR/Library_System/app/controllers/cardholder_personal_infos_controller.rb
class CardholderPersonalInfosController < ApplicationController
  before_action :set_cardholder_personal_info, only: [:show, :edit, :update, :destroy]

  # GET /cardholder_personal_infos
  # GET /cardholder_personal_infos.json
  def index
    @cardholder_personal_infos = CardholderPersonalInfo.all
  end

  # GET /cardholder_personal_infos/1
  # GET /cardholder_personal_infos/1.json
  def show
  end

  # GET /cardholder_personal_infos/new
  def new
    @cardholder_personal_info = CardholderPersonalInfo.new
  end

  # GET /cardholder_personal_infos/1/edit
  def edit
  end

  # POST /cardholder_personal_infos
  # POST /cardholder_personal_infos.json
  def create
    @cardholder_personal_info = CardholderPersonalInfo.new(cardholder_personal_info_params)

    respond_to do |format|
      if @cardholder_personal_info.save
        format.html { redirect_to @cardholder_personal_info, notice: 'Cardholder personal info was successfully created.' }
        format.json { render :show, status: :created, location: @cardholder_personal_info }
      else
        format.html { render :new }
        format.json { render json: @cardholder_personal_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cardholder_personal_infos/1
  # PATCH/PUT /cardholder_personal_infos/1.json
  def update
    respond_to do |format|
      if @cardholder_personal_info.update(cardholder_personal_info_params)
        format.html { redirect_to @cardholder_personal_info, notice: 'Cardholder personal info was successfully updated.' }
        format.json { render :show, status: :ok, location: @cardholder_personal_info }
      else
        format.html { render :edit }
        format.json { render json: @cardholder_personal_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cardholder_personal_infos/1
  # DELETE /cardholder_personal_infos/1.json
  def destroy
    @cardholder_personal_info.destroy
    respond_to do |format|
      format.html { redirect_to cardholder_personal_infos_url, notice: 'Cardholder personal info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cardholder_personal_info
      @cardholder_personal_info = CardholderPersonalInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cardholder_personal_info_params
      params.require(:cardholder_personal_info).permit(:name, :lastname, :email, :phone_num, :home_num, :street, :city, :state, :zip, :cardholder_id)
    end
end

Library_ROR/Library_System/app/helpers/cardholder_personal_infos_helper.rb
module CardholderPersonalInfosHelper
end

Library_ROR/Library_System/app/views/cardholder_personal_infos/_form.html.erb
<%= form_for(cardholder_personal_info) do |f| %>
  <% if cardholder_personal_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cardholder_personal_info.errors.count, "error") %> prohibited this cardholder_personal_info from being saved:</h2>

      <ul>
      <% cardholder_personal_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :lastname %>
    <%= f.text_field :lastname %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :phone_num %>
    <%= f.number_field :phone_num %>
  </div>

  <div class="field">
    <%= f.label :home_num %>
    <%= f.number_field :home_num %>
  </div>

  <div class="field">
    <%= f.label :street %>
    <%= f.text_field :street %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :zip %>
    <%= f.number_field :zip %>
  </div>

  <div class="field">
    <%= f.label :cardholder_id %>
    <%= f.number_field :cardholder_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Library_ROR/Library_System/app/views/cardholder_personal_infos/edit.html.erb
<h1>Editing Cardholder Personal Info</h1>

<%= render 'form', cardholder_personal_info: @cardholder_personal_info %>

<%= link_to 'Show', @cardholder_personal_info %> |
<%= link_to 'Back', cardholder_personal_infos_path %>

Library_ROR/Library_System/app/views/cardholder_personal_infos/index.html.erb
<!--<p id="notice"><%= notice %></p>-->

<h1 align="center">Cardholder Personal Infos</h1>

<div class="container">
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>Phone num</th>
      <th>Home num</th>
      <th>Street</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Cardholder</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cardholder_personal_infos.each do |cardholder_personal_info| %>
      <tr>
        <td><%= cardholder_personal_info.name %></td>
        <td><%= cardholder_personal_info.lastname %></td>
        <td><%= cardholder_personal_info.email %></td>
        <td><%= cardholder_personal_info.phone_num %></td>
        <td><%= cardholder_personal_info.home_num %></td>
        <td><%= cardholder_personal_info.street %></td>
        <td><%= cardholder_personal_info.city %></td>
        <td><%= cardholder_personal_info.state %></td>
        <td><%= cardholder_personal_info.zip %></td>
        <td><%= cardholder_personal_info.cardholder_id %></td>
        <td><%= link_to 'Show', cardholder_personal_info %></td>
        <td><%= link_to 'Edit', edit_cardholder_personal_info_path(cardholder_personal_info) %></td>
        <td><%= link_to 'Destroy', cardholder_personal_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>


<%= link_to 'New Cardholder Personal Info', new_cardholder_personal_info_path %>

Library_ROR/Library_System/app/views/cardholder_personal_infos/new.html.erb
<h1>New Cardholder Personal Info</h1>

<%= render 'form', cardholder_personal_info: @cardholder_personal_info %>

<%= link_to 'Back', cardholder_personal_infos_path %>

Library_ROR/Library_System/app/views/cardholder_personal_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cardholder_personal_info.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @cardholder_personal_info.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @cardholder_personal_info.email %>
</p>

<p>
  <strong>Phone num:</strong>
  <%= @cardholder_personal_info.phone_num %>
</p>

<p>
  <strong>Home num:</strong>
  <%= @cardholder_personal_info.home_num %>
</p>

<p>
  <strong>Street:</strong>
  <%= @cardholder_personal_info.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @cardholder_personal_info.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @cardholder_personal_info.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @cardholder_personal_info.zip %>
</p>

<p>
  <strong>Cardholder:</strong>
  <%= @cardholder_personal_info.cardholder_id %>
</p>

<%= link_to 'Edit', edit_cardholder_personal_info_path(@cardholder_personal_info) %> |
<%= link_to 'Back', cardholder_personal_infos_path %>