Library_ROR/Library_System/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  #resource :session, :only => [:new, :create, :destroy]
  #match 'signup' => 'users#new', :as => :signup
  #match 'register' => 'users#create', :as => :register
  #match 'login' => 'sessions#new', :as => :login
  #match 'logout' => 'sessions#destroy', :as => :logout

  	#match 'activate/:activation_code' => 'users#activate', :as => activate, :activation_code => nil
 	#resources :support_issues 



  resources :cardholder_accounts
  get 'pages/home'
  root 'pages#home'


  resources :cardholder_personal_infos
  resources :materials
  resources :fines
  resources :checkouts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Library_ROR/Library_System/app/models/fine.rb
class Fine < ApplicationRecord

	#belongs_to  :cardholder_account

	validates_uniqueness_of :fine_id
end

Library_ROR/Library_System/app/controllers/fines_controller.rb
class FinesController < ApplicationController
  before_action :set_fine, only: [:show, :edit, :update, :destroy]

  # GET /fines
  # GET /fines.json
  def index
    @fines = Fine.all
  end

  # GET /fines/1
  # GET /fines/1.json
  def show
  end

  # GET /fines/new
  def new
    @fine = Fine.new
  end

  # GET /fines/1/edit
  def edit
  end

  # POST /fines
  # POST /fines.json
  def create
    @fine = Fine.new(fine_params)

    respond_to do |format|
      if @fine.save
        format.html { redirect_to @fine, notice: 'Fine was successfully created.' }
        format.json { render :show, status: :created, location: @fine }
      else
        format.html { render :new }
        format.json { render json: @fine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fines/1
  # PATCH/PUT /fines/1.json
  def update
    respond_to do |format|
      if @fine.update(fine_params)
        format.html { redirect_to @fine, notice: 'Fine was successfully updated.' }
        format.json { render :show, status: :ok, location: @fine }
      else
        format.html { render :edit }
        format.json { render json: @fine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fines/1
  # DELETE /fines/1.json
  def destroy
    @fine.destroy
    respond_to do |format|
      format.html { redirect_to fines_url, notice: 'Fine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fine
      @fine = Fine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fine_params
      params.require(:fine).permit(:date_of_fine, :amount, :cardholder_id, :fine_id)
    end
end

Library_ROR/Library_System/app/helpers/fines_helper.rb
module FinesHelper
end

Library_ROR/Library_System/app/views/fines/_form.html.erb
<%= form_for(fine) do |f| %>
  <% if fine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fine.errors.count, "error") %> prohibited this fine from being saved:</h2>

      <ul>
      <% fine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date_of_fine %>
    <%= f.date_select :date_of_fine %>
  </div>

  <div class="field">
    <%= f.label :amount %>
    <%= f.text_field :amount %>
  </div>

  <div class="field">
    <%= f.label :cardholder_id %>
    <%= f.number_field :cardholder_id %>
  </div>

  <div class="field">
    <%= f.label :fine_id %>
    <%= f.number_field :fine_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Library_ROR/Library_System/app/views/fines/edit.html.erb
<h1>Editing Fine</h1>

<%= render 'form', fine: @fine %>

<%= link_to 'Show', @fine %> |
<%= link_to 'Back', fines_path %>

Library_ROR/Library_System/app/views/fines/index.html.erb
<!--<p id="notice"><%= notice %></p>-->

<h1 align="center">Fines</h1>


<div class="container">
<table class="table">
  <thead>
    <tr>
      <th>Date of fine</th>
      <th>Amount</th>
      <th>Cardholder</th>
      <th>Fine</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fines.each do |fine| %>
      <tr>
        <td><%= fine.date_of_fine %></td>
        <td><%= fine.amount %></td>
        <td><%= fine.cardholder_id %></td>
        <td><%= fine.fine_id %></td>
        <td><%= link_to 'Show', fine %></td>
        <td><%= link_to 'Edit', edit_fine_path(fine) %></td>
        <td><%= link_to 'Destroy', fine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>


<%= link_to 'New Fine', new_fine_path %>

Library_ROR/Library_System/app/views/fines/new.html.erb
<h1>New Fine</h1>

<%= render 'form', fine: @fine %>

<%= link_to 'Back', fines_path %>

Library_ROR/Library_System/app/views/fines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date of fine:</strong>
  <%= @fine.date_of_fine %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @fine.amount %>
</p>

<p>
  <strong>Cardholder:</strong>
  <%= @fine.cardholder_id %>
</p>

<p>
  <strong>Fine:</strong>
  <%= @fine.fine_id %>
</p>

<%= link_to 'Edit', edit_fine_path(@fine) %> |
<%= link_to 'Back', fines_path %>