Library_ROR/Library_System/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  #resource :session, :only => [:new, :create, :destroy]
  #match 'signup' => 'users#new', :as => :signup
  #match 'register' => 'users#create', :as => :register
  #match 'login' => 'sessions#new', :as => :login
  #match 'logout' => 'sessions#destroy', :as => :logout

  	#match 'activate/:activation_code' => 'users#activate', :as => activate, :activation_code => nil
 	#resources :support_issues 



  resources :cardholder_accounts
  get 'pages/home'
  root 'pages#home'


  resources :cardholder_personal_infos
  resources :materials
  resources :fines
  resources :checkouts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Library_ROR/Library_System/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

  <!-- website title -->
    <title>Library System</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>

<!-- V4: Navagation bar -->
  <nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div id="navbar" class="collapse navbar-collapse">
     
    <!--logo is linked to home page -->
    <%= link_to (image_tag("Library-System_logo.png", alt: "Library-System Logo")), root_path, id:"logo" %>

    <ul class="nav navbar-nav navbar-right navbar-text pull-right">

      <!--logic to check if user is signed in or not to show appropriate links-->
      <% if user_signed_in? %>
        <li class="showUserEmail"> Hello, <strong><%= current_user.email %></strong>! </li>
        <li><%= link_to 'Checkout', checkouts_path %></li>
        <li><%= link_to 'Cardholders', cardholder_accounts_path %></li>
        <li><%= link_to 'Fines', fines_path %></li>
        <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li> 
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %><li> 
      <% else %> 
        <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %></li>
        <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link' %></li>
      <% end %>
    </ul>   
    </div>
  </div>
  </nav>
  
  <br />
  <br />


<!-- DEVISE alerts -->
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

  <!-- Yield method inserts the contents of each page into the site layout -->
  <%= yield %>

<br />


<footer class="footer">
  <small> 
  The Library System Project Fall 2016 &copy;
  </small>
  <small class="footerNames container-fluid text-center">
  Created and Developed By: Jazmin Andrade, Karla Flores, Zach Gordon, &amp; Guy Zarko.
  </small>
</footer>

  </body>
</html>